### ISSUE TITLE
advanced_search property_list

### ISSUE THREAD

**Issue by epatyukova** [lrcfmd/ICSDClient#2]
When doing an advanced search for more than 500 entries only "CollectionCode" and "StructuredFormula" were returned. The problem was found in fetch_data method where it called itself recursively with the default property list, which contained only "CollectionCode" and "StructuredFormula". So, the non-default property_list needs to be added

**Comment by SurgeArrester** [comment]
Meregd as part of https://github.com/lrcfmd/ICSDClient/pull/3#event-7867068825
